// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBLS2qVZk4VNdYleyx1-UBFL3rZz3TFg',
    appId: '1:335864851774:web:ab4b94cefc5e4a8785d06f',
    messagingSenderId: '335864851774',
    projectId: 'coffeeshopapp-d8de6',
    authDomain: 'coffeeshopapp-d8de6.firebaseapp.com',
    storageBucket: 'coffeeshopapp-d8de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGdI6yTX6OMCdnBsxNx5KTXtwThUf8ZJA',
    appId: '1:335864851774:ios:3814af318c68857485d06f',
    messagingSenderId: '335864851774',
    projectId: 'coffeeshopapp-d8de6',
    storageBucket: 'coffeeshopapp-d8de6.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGdI6yTX6OMCdnBsxNx5KTXtwThUf8ZJA',
    appId: '1:335864851774:ios:3814af318c68857485d06f',
    messagingSenderId: '335864851774',
    projectId: 'coffeeshopapp-d8de6',
    storageBucket: 'coffeeshopapp-d8de6.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATBLS2qVZk4VNdYleyx1-UBFL3rZz3TFg',
    appId: '1:335864851774:web:ff8583bd8b9ed2dc85d06f',
    messagingSenderId: '335864851774',
    projectId: 'coffeeshopapp-d8de6',
    authDomain: 'coffeeshopapp-d8de6.firebaseapp.com',
    storageBucket: 'coffeeshopapp-d8de6.firebasestorage.app',
  );
}
